# Generated by Django 2.0.6 on 2019-01-27 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0004_auto_20190127_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='dateAdded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='deadLine',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='description',
            field=models.CharField(default="django.utils.timezone.now", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='duration',
            field=models.CharField(default="django.utils.timezone.now", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='studentsApproved',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='studentsEnrolled',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='title',
            field=models.CharField(default=' Internship ', max_length=150),
            preserve_default=False,
        ),
    ]
