# Generated by Django 2.0.6 on 2019-01-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0005_auto_20190127_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='studentsApproved',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='intern',
            name='studentsEnrolled',
            field=models.CharField(max_length=200),
        ),
    ]
