# Generated by Django 2.0.6 on 2019-01-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0006_auto_20190127_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='eligibility',
            field=models.CharField(default='Kids', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='place',
            field=models.CharField(default='MEC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='stiphend',
            field=models.CharField(default='No', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intern',
            name='deadLine',
            field=models.CharField(max_length=50),
        ),
    ]
