# Generated by Django 2.0.6 on 2019-01-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0009_profile_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leisureTime',
            field=models.CharField(default='Thrusday evening', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intern',
            name='studentsApproved',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intern',
            name='studentsEnrolled',
            field=models.CharField(default='', max_length=200),
        ),
    ]
