# Generated by Django 2.0.6 on 2019-01-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0010_auto_20190129_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='discipline',
            field=models.CharField(default='CSE', max_length=10),
            preserve_default=False,
        ),
    ]
