# Generated by Django 2.0.6 on 2019-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0011_intern_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='discipline',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL'), ('MECH', 'MECH'), ('Management', 'Management'), ('Humanities', 'Humanities')], default='CSE', max_length=10),
        ),
    ]
