# Generated by Django 2.0.6 on 2019-01-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0012_auto_20190130_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='discipline',
            field=models.CharField(max_length=10),
        ),
    ]
