# Generated by Django 2.0.6 on 2019-02-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0013_auto_20190131_0421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('student', 'Student'), ('professor', 'Professor'), ('admin', 'Admin'))},
        ),
    ]
