# Generated by Django 2.0.6 on 2019-02-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0014_auto_20190209_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilePhoto',
        ),
    ]
