# Generated by Django 2.0.6 on 2019-02-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0015_remove_profile_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePhoto',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
