# Generated by Django 2.0.6 on 2019-02-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0016_profile_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrolledInternships',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
